In [2]:
#copied from starter code
# Dependencies and Setup
import hvplot.pandas
import pandas as pd
import requests
from pathlib import Path

import sys
import os

# Import API key
path = os.path.abspath("../Starter_Code/starter_code")
sys.path.append(path)
from api_keys import geoapify_key

In [3]:
# Load the CSV file created in Part 1 into a Pandas DataFrame
csv_file = Path("output_data/cities.csv")
city_data_df = pd.read_csv(csv_file)

# Display sample data
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,edinburgh of the seven seas,-37.0676,-12.3116,14.08,81,92,10.73,SH,1688821752
1,1,grytviken,-54.2811,-36.5092,-6.97,81,18,4.71,GS,1688821753
2,2,dolores,-36.3132,-57.6792,8.41,71,100,2.76,AR,1688821691
3,3,prince rupert,54.3161,-130.3201,15.07,91,82,0.35,CA,1688821754
4,4,port-aux-francais,-49.3500,70.2167,1.85,76,100,6.05,TF,1688821754

In [ ]:
%%capture --no-display

# Configure the map plot
# YOUR CODE HERE

# Display the map
# YOUR CODE HERE